name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # è§¦å‘åˆ†æ”¯ï¼Œæ ¹æ®éœ€è¦ä¿®æ”¹
permissions:
  contents: read
  packages: write   # ğŸ‘ˆ å¿…é¡»åŠ è¿™ä¸ª
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # æ£€å‡ºä»£ç 
      - name: Checkout repository
        uses: actions/checkout@v3

      # ç™»å½•åˆ° GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # æ„å»º Docker é•œåƒ
      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:latest
          docker build -t $IMAGE_NAME .

      # æ¨é€ Docker é•œåƒ
      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:latest
          docker push $IMAGE_NAME
